class AimDLLWrapperException(Exception):
    ...

class AimDLLWrapperFunctionDoesNotExistError(AimDLLWrapperException):
    ...

class AimDLLWrapperFunctionInitializationError(AimDLLWrapperException):
    ...