class BaseAimImporterException(Exception):
    ...

class AimImporterFileNotFoundError(BaseAimImporterException):
    ...

class AimImporterFailedToParseFileError(BaseAimImporterException):
    ...

class AimImporterFailedToCloseFileError(BaseAimImporterException):
    ...

class AimImporterFailedToReadFileError(BaseAimImporterException):
    ...

class AimImporterInternalSystemError(BaseAimImporterException):
    ...

class AimImporterNoSessionPresentError(BaseAimImporterException):
    ...

class AimImporterNoChannelSamplesPresentError(BaseAimImporterException):
    ...

class AimImporterInvalidGPSFrequencyError(BaseAimImporterException):
    ...